spring:
  datasource:
    url: jdbc:h2:mem:rbadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  kafka:
    bootstrap-servers: localhost:9092
    consumers:
      card-status:
        enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      listener:
        missing-topics-fatal: false
